---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-readonly
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: "${CLUSTER_READ_ONLY_GROUP}" # aks-reader-rbac-group / Reader

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-readonly-more-view
rules:
  - apiGroups:
      - 'secrets-store.csi.x-k8s.io'
    resources:
      - 'secretproviderclasses'
    verbs:
      - 'create'
      - 'update'
      - 'delete'
      - 'watch'
      - 'list'
      - 'get'
  - apiGroups:
      - 'helm.fluxcd.io'
    resources:
      - 'helmreleases'
    verbs:
      - 'list'
      - 'get'
  - apiGroups:
      - 'helm.toolkit.fluxcd.io'
    resources:
      - 'helmreleases'
    verbs:
      - 'list'
      - 'get'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-readonly-more-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-readonly-more-view
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: "${CLUSTER_READ_ONLY_GROUP}"
