apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: aks-pod-identity-mi
  namespace: admin
spec:
  type: 0
  resourceID: MI_RESOURCE_ID
  clientID: MI_CLIENTID

---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: aks-pod-identity-mi-binding
  namespace: admin
spec:
  azureIdentity: aks-pod-identity-mi
  selector: aks-pod-identity-mi
