apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: aks-pod-identity-mi
  namespace: admin
spec:
  type: 0
  resourceID: /subscriptions/d7b54c7f-c2c9-41ee-930d-7056ebbb5bde/resourcegroups/mgmt_test_kubernetes_resource_group/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aks-pod-identity-mi
  clientID: 9e85dcd6-ad32-4a71-8255-726515885509

---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: aks-pod-identity-mi-binding
  namespace: admin
spec:
  azureIdentity: aks-pod-identity-mi
  selector: aks-pod-identity-mi
