apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: aks-pod-identity-mi
  namespace: admin
spec:
  type: 0
  resourceID: /subscriptions/867a878b-cb68-4de5-9741-361ac9e178b6/resourceGroups/genesis_resource_group/providers/Microsoft.ManagedIdentity/userAssignedIdentities/flux-dev-mi-sops
  clientID: 2914d4ab-bad7-4d9b-80ca-2e0f7ef1350e

---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: aks-pod-identity-mi-binding
  namespace: admin
spec:
  azureIdentity: aks-pod-identity-mi
  selector: aks-pod-identity-mi
